### PR TITLE
Fix of hydration and update of goober version

### PR DESCRIPTION
**Pull request by SogoCZE**
Hello,

I've fix hydration of styled components and also update solid and goober version to newest in package.json. I also update the package version.

### CODE REVIEW

**Comment by ryansolid** [comment]
Hmm this actually broke my example: https://codesandbox.io/s/solid-styled-components-yv2t1?file=/index.js. Looking into it now.

**Comment by ryansolid** [comment]
I know what it is.. we lost reactivity. I will fix it up.

**Comment by ryansolid** [comment]
FIxed 0.28.3

**Comment by SogoCZE** [comment]
> FIxed 0.28.3

Thanks! It was because I used spread operator instead of mergeProps and also i didn't make proper getter for children, I see. Noted. I am still pretty new to the Solid magic :).

**Pull request merged**
